import Topbar from '@/ui/Topbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Topbar />
        <h1>Home layout</h1>
        {children}
      </body>
    </html>
  );
}
